

services:
  db:
    image: postgres:16
    container_name: atlas_postgres
    restart: always
    environment:
      POSTGRES_USER: atlas_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: atlas_db
    ports:
      - "5432:5432"
    volumes:
      - atlas_pgdata:/var/lib/postgresql/data

volumes:
  atlas_pgdata: