services:
  db:
    image: postgres:17
    container_name: tadreeby-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tadreeby

    ports:
      - "5432:5432"

    volumes:
      - tadreeby_pgdata:/var/lib/postgresql/data

volumes:
  tadreeby_pgdata: